### ISSUE TITLE
Paired Bracket Not Highlighted in SQL Files

### ISSUE THREAD

**Issue by Seaweed0112** [nervenes/zed-sql#6] opened 2024-08-18 00:27 UTC
Hello,

I've noticed an issue in Zed Editor when working with SQL files. When the cursor is positioned at one bracket (e.g., ( or {), the corresponding paired bracket is not highlighted. This makes it difficult to locate and match the paired bracket, especially in complex SQL queries.

This issue affects the user experience as it hampers quick navigation and readability within the code.

Steps to reproduce:

Open an SQL file in Zed Editor.
Place the cursor on any opening or closing bracket (e.g., ( or {).
Observe that the corresponding paired bracket is not highlighted.
Expected behavior:
The corresponding paired bracket should be highlighted when the cursor is placed on one bracket, similar to the behavior in other file types.

Thank you for looking into this issue. I hope it can be resolved in a future update.
![image](https://github.com/user-attachments/assets/fc698d60-065f-449d-bbcf-44105ffd0930)

Environment
Zed: v0.148.1 (Zed)
OS: macOS 15.0.0
Memory: 16 GiB
Architecture: aarch64

**Comment by nervenes** [comment] 2024-08-27 16:36
This should work as of https://github.com/nervenes/zed-sql/pull/4, @phileix do you happen to know the issue here? maybe the schema is incorrect

**Comment by phileix** [comment] 2024-08-28 09:47
Hmm, that is strange, I just tried it with that exact query and cannot reproduce the problem, I am getting the proper highlighting. Does the highlighting work for you with other languages?

I only added round brackets to the schema for SQL though, curly and square would have to be added, if we want highlighting for them.

**Comment by Seaweed0112** [comment] 2024-11-10 05:23
I found out it works fine now. 
![image](https://github.com/user-attachments/assets/0881fadc-9584-4a56-88a4-602e1c343139)

**Comment by phileix** [comment] 2024-11-13 15:05
Good to hear. @nervenes I think we can close this issue then.

**Closed** 2024-11-13 15:17 UTC
